[package]
name = "kattis-rs"
version = "1.0.2"
authors = ["Marcel H Rød <marcelroed@gmail.com>"]
edition = "2018"
homepage = "https://github.com/marcelroed/"
repository = "https://github.com/marcelroed/kattis-rs"
description = "Competitive programming checker for open.kattis.com"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kattis-rs"
path = "src/main.rs"


[dependencies]
reqwest = {version = "0.10", features = ["blocking"]}
tempfile = "3"
zip = "0"
clap = "3.0.0-beta.1"
futures = "0.3"
tokio = { version = "0.2", features = ["full"] }
walkdir = "2"
colored = "2"
itertools = "0.9"
float-cmp = "0.8"
enum-iterator = "0.6"
regex = "1"
lazy_static = "1.4.0"
