[package]
name = "kattis-rs"
version = "0.2.0"
authors = ["Marcel H Rød <marcelroed@gmail.com>"]
edition = "2018"
homepage = "https://github.com/marcelroed/"
repository = "https://github.com/marcelroed/kattis-rs"
description = "Competitive programming checker for open.kattis.com"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "kattis-rs"
path = "src/main.rs"


[dependencies]
reqwest = {version = "0.10.8", features = ["blocking"]}
tempfile = "3.1.0"
zip = "0.5.6"
clap = "3.0.0-beta.1"
futures = "0.3.5"
tokio = { version = "0.2.22", features = ["full"] }
walkdir = "2.3.1"
colored = "2"
itertools = "0.9.0"
float-cmp = "0.8.0"
enum-iterator = "0.6.0"
